# Router Simulator Configuration
# Multi-cloud networking platform with CloudPods and Aviatrix integration

server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  enable_cors: true
  enable_pprof: false

log:
  level: "info"
  json: false
  file: ""

analytics:
  enabled: true
  clickhouse:
    host: "localhost"
    port: 9000
    database: "router_sim"
    username: "default"
    password: ""
    ssl: false
  prometheus:
    enabled: true
    path: "/metrics"
    port: 9090

cloudpods:
  enabled: false
  api:
    base_url: "https://localhost:8080"
    version: "v1"
    timeout: "30s"
  auth:
    type: "basic"
    username: "admin"
    password: ""
  timeout: "30s"
  region: "default"
  projects: []

aviatrix:
  enabled: false
  controller:
    host: "localhost"
    port: 443
    username: "admin"
    password: ""
    ssl: true
  copilot:
    host: "localhost"
    port: 443
    username: "admin"
    password: ""
    ssl: true
  timeout: "30s"

router:
  interfaces:
    - name: "eth0"
      ip_address: "192.168.1.1"
      netmask: "255.255.255.0"
      mtu: 1500
      enabled: true
    - name: "eth1"
      ip_address: "10.0.0.1"
      netmask: "255.255.0.0"
      mtu: 1500
      enabled: true

  protocols:
    - type: "bgp"
      name: "BGP"
      enabled: true
      parameters:
        asn: 65001
        router_id: "192.168.1.1"
    - type: "ospf"
      name: "OSPF"
      enabled: true
      parameters:
        router_id: "192.168.1.1"
        area: 0
    - type: "isis"
      name: "ISIS"
      enabled: false
      parameters:
        system_id: "1921.6801.0001"
        level: 2

  traffic_shaping:
    algorithm: "token_bucket"
    rate: 1000000
    burst_size: 100000
    enabled: true
    parameters:
      queues: 8
      weights: [1, 2, 4, 8, 16, 32, 64, 128]

  impairments:
    - interface: "eth0"
      type: "delay"
      enabled: true
      parameters:
        delay: 100
        jitter: 10
    - interface: "eth1"
      type: "loss"
      enabled: true
      parameters:
        loss: 0.01

