version: '3.8'

services:
  router-sim:
    build: .
    ports:
      - "8080:8080"  # Web interface
      - "8081:8081"  # API
      - "9000:9000"  # ClickHouse
    volumes:
      - ./config:/etc/router-sim
      - ./scenarios:/etc/router-sim/scenarios
    environment:
      - ROUTER_CONFIG=/etc/router-sim/router.yaml
      - LOG_LEVEL=info
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=router_sim

volumes:
  clickhouse_data:
