#!/bin/bash

# Show help for Terraform provider generator
set -e

echo "Terraform Provider Generator Help"
echo "================================="
echo ""
echo "Available commands:"
echo ""
echo "  ./scripts/install_dependencies.sh  - Install required dependencies"
echo "  ./scripts/check_health.sh          - Check system health"
echo "  ./scripts/generate_all.sh          - Generate all providers"
echo "  ./scripts/test_providers.sh        - Test generated providers"
echo "  ./scripts/validate_terraform.sh    - Validate Terraform configurations"
echo "  ./scripts/deploy_providers.sh      - Deploy providers"
echo "  ./scripts/update_providers.sh      - Update providers"
echo "  ./scripts/backup_providers.sh      - Backup providers"
echo "  ./scripts/restore_providers.sh     - Restore providers from backup"
echo "  ./scripts/cleanup.sh               - Clean up generated files"
echo "  ./scripts/run_tests.sh             - Run all tests"
echo ""
echo "Manual commands:"
echo ""
echo "  go run main.go cloudpods <output_dir>     - Generate CloudPods provider"
echo "  go run main.go aviatrix <output_dir>      - Generate Aviatrix provider"
echo "  go run main.go router-sim <output_dir>    - Generate Router Simulator provider"
echo ""
echo "Make targets:"
echo ""
echo "  make build      - Build the generator"
echo "  make run        - Run the generator (requires PROVIDER and OUTPUT_DIR)"
echo "  make clean      - Clean build artifacts"
echo "  make test       - Run tests"
echo "  make install    - Install dependencies"
echo "  make cloudpods  - Generate CloudPods provider"
echo "  make aviatrix   - Generate Aviatrix provider"
echo "  make router-sim - Generate Router Simulator provider"
echo "  make all        - Generate all providers"
echo "  make help       - Show this help"
echo ""
echo "Examples:"
echo ""
echo "  # Generate all providers"
echo "  ./scripts/generate_all.sh"
echo ""
echo "  # Generate specific provider"
echo "  go run main.go cloudpods ./output/cloudpods"
echo ""
echo "  # Test generated providers"
echo "  ./scripts/test_providers.sh"
echo ""
echo "  # Deploy providers"
echo "  ./scripts/deploy_providers.sh"
echo ""
echo "  # Backup providers"
echo "  ./scripts/backup_providers.sh"
echo ""
echo "  # Restore providers"
echo "  ./scripts/restore_providers.sh backup/20240101_120000"
echo ""
echo "For more information, see README.md"
