[package]
name = "router_sim_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "router_sim_rust"
crate-type = ["cdylib", "rlib"]

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tokio-util = "0.7"
futures = "0.3"

# Networking
pcap = "1.0"
libc = "0.2"
nix = "0.27"

# Performance
rayon = "1.7"
crossbeam = "0.8"
dashmap = "5.4"
parking_lot = "0.12"

# Async runtime
async-trait = "0.1"
futures-util = "0.3"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# Serialization
bincode = "1.3"
rmp-serde = "1.1"

# Math and algorithms
nalgebra = "0.32"
petgraph = "0.6"
rand = "0.8"

# System monitoring
sysinfo = "0.29"
procfs = "0.15"

# FFI
libffi = "0.1"

[build-dependencies]
cbindgen = "0.24"

[features]
default = ["std"]
std = []
no_std = []

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
